title: My Personal Diary
description: A place for my thoughts, lessons, and experiences
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
